services:
  - type: web
    name: daily-log-ai
    env: python  # âœ… this enables runtime.txt support
    plan: free
    buildCommand: ./render/build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
